In [2]:
import keras
from keras.utils import Sequence
import numpy as np
from keras.layers import *
from keras.losses import mean_squared_error
from keras.callbacks import *
import os

import pickle
import random
from tqdm import tqdm

from landlordai.game.player import LearningPlayer_v1

Using TensorFlow backend.


In [15]:
composite15 = keras.models.load_model('combined15.h5')
composite0 = keras.models.load_model('combined0.h5')
composite1 = keras.models.load_model('combined1.h5')

In [3]:
history_matrix = np.zeros((100, 21))
history_matrix[0, 19] = 1
history_matrix[1, 19] = 1

In [6]:
hand_vector = np.array([0., 1., 0., 1., 1., 2., 1., 2., 3., 2., 2., 0., 2., 0., 0., 0., 0., 0.])
move_vector = [0] * 21
move_vector[-2] = 1

In [13]:
composite.predict(x=[np.array([history_features]), np.array([move_vector]), np.array([hand_vector])])

array([[-0.04627341]], dtype=float32)

In [5]:
with open('irregular.pkl', 'rb') as f:
    a_set, index = pickle.load(f)

In [11]:
history_features = a_set[0][0][index]
move_vector = a_set[0][1][index]
hand_vector = a_set[0][2][index]
q = a_set[1][index]

In [16]:
composite0.predict(x=[np.array([history_features]), np.array([move_vector]), np.array([hand_vector])])

array([[-0.02582265]], dtype=float32)

In [17]:
composite1.predict(x=[np.array([history_features]), np.array([move_vector]), np.array([hand_vector])])

array([[-0.00698726]], dtype=float32)

In [18]:
composite15.predict(x=[np.array([history_features]), np.array([move_vector]), np.array([hand_vector])])

array([[0.01577937]], dtype=float32)

In [ ]:
player = 