In [1]:
!pip install landlord-ai --upgrade
!pip install keras.preprocessing --user
!pip install tqdm

  Created wheel for landlord-ai: filename=landlord_ai-0.1.8-py3-none-any.whl size=14153 sha256=eaa6f50d753ec67cb46b59e676f4869c97c8d289ceff6f999cb8ab26ffc3ffb0
  Stored in directory: /home/jupyter/.cache/pip/wheels/ae/97/17/57fe3a2136f43f8ce1b7cd176a36203ff4c8b5402f3f2815f5
Successfully built landlord-ai
     |████████████████████████████████| 41 kB 793 kB/s eta 0:00:011


In [1]:
import keras
from keras.utils import Sequence
import numpy as np
from keras.layers import *
from keras.losses import mean_squared_error
from keras.callbacks import *
import os

import pickle
import random
from tqdm import tqdm

from landlordai.game.player import LearningPlayer_v1

Using TensorFlow backend.


In [2]:
class DataGenerator(Sequence):
    """Generates data for Keras
    Sequence based data generator. Suitable for building data generator for training and prediction.
    """
    def __init__(self, path_ids, batch_size=1024, shuffle=True, clamp=False):
        """Initialization
        :param list_IDs: list of all 'label' ids to use in the generator
        :param labels: list of image labels (file names)
        :param image_path: path to images location
        :param mask_path: path to masks location
        :param to_fit: True to return X and y, False to return X only
        :param batch_size: batch size at each iteration
        :param dim: tuple indicating image dimension
        :param n_channels: number of image channels
        :param n_classes: number of output masks
        :param shuffle: True to shuffle label indexes after every epoch
        """
        self.path_ids = path_ids
        self.batch_size = batch_size
        self.shuffle = shuffle
        self.clamp = clamp
        
        self.load_cache()

    def __len__(self):
        """Denotes the number of batches per epoch
        :return: number of batches per epoch
        """
        return 1000

    def load_cache(self):
        with open(random.choice(self.path_ids), 'rb') as f:
            history_matrices, move_vectors, hand_vectors, y = pickle.load(f)
            
            if self.shuffle:
                p = np.random.permutation(len(history_matrices))
                
                history_matrices = np.array(history_matrices)[p]
                move_vectors = move_vectors[p]
                hand_vectors = hand_vectors[p]
                y = y[p]
        
        # unflatten
        history_matrices = self.densify(history_matrices)

        self.cache = (history_matrices, move_vectors, hand_vectors, y) 
        self.curr_index = 0
        
    
    def __getitem__(self, index):
        """Generate one batch of data
        :param index: index of the batch
        :return: X and y when fitting. X only when predicting
        """
        limit = min(len(self.cache[0]), (self.curr_index + 1) * self.batch_size)
        
        #print(self.curr_index * self.batch_size, limit)
        history_matrices = self.cache[0][self.curr_index * self.batch_size: limit]
        move_vectors = self.cache[1][self.curr_index * self.batch_size: limit]
        hand_vectors = self.cache[2][self.curr_index * self.batch_size: limit]
        #print(self.curr_index * self.batch_size, limit)
        y = self.cache[3][self.curr_index * self.batch_size: limit]
        self.curr_index += 1
        
        # load a new batch
        if (self.curr_index + 1) * self.batch_size >= len(self.cache[0]):
            self.load_cache()
        
        return [history_matrices, move_vectors, hand_vectors], self.adjust_y(y)

    def densify(self, sparse_matrix):
        return np.array([x.todense() for x in sparse_matrix])

    def adjust_y(self, y):
        if not self.clamp:
            return y
        new_y = []
        for elem in y:
            if abs(int(elem) - elem) > 1E-4:
                new_y.append(0)
            else:
                new_y.append(elem)
        return np.array(new_y)



In [4]:
data_folder = '3_30_sim6'

In [54]:
assert data_folder is not None
!rm -r ../data/$data_folder
!gsutil -m cp -r gs://landlord_ai/$data_folder ../data/

Copying gs://landlord_ai/3_30_sim6/0.pkl...
Copying gs://landlord_ai/3_30_sim6/1.pkl...
Copying gs://landlord_ai/3_30_sim6/2.pkl...
Copying gs://landlord_ai/3_30_sim6/3.pkl...
Copying gs://landlord_ai/3_30_sim6/4.pkl...
/ [5/5 files][693.6 MiB/693.6 MiB] 100% Done                                    
Operation completed over 5 objects/693.6 MiB.                                    


In [5]:

directory = '../data/' + data_folder
filenames = [directory + '/' + file for file in os.listdir(directory)]

if len(filenames) == 1:
    train_path_ids = filenames
    test_path_ids = filenames
else:
    divider = int(len(filenames) * 0.9)
    train_path_ids = filenames[:divider]
    test_path_ids = filenames[divider:]

In [51]:
# quality control
inspector = DataGenerator(filenames, shuffle=False)

In [53]:
irregularities = 0
for j in tqdm(range(100)):
    a_set = inspector[j]
    for i in range(1000):
        history = a_set[0][0][i]
        history_sum = np.sum(history)
        q = a_set[1][i]
        irregular = abs(q) > 1 and history_sum < 20
        if irregular:
            #with open('irregular.pkl', 'wb') as f:
            #    pickle.dump((a_set, i), f)
            irregularities += 1
            print(history, q)
        #assert not (abs(q) > 1 and history_sum < 10)

 44%|████▍     | 44/100 [00:00<00:00, 103.21it/s]

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] -2.5543797281384473


 76%|███████▌  | 76/100 [00:06<00:02,  8.25it/s] 

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] -4.361495311185718
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] -4.510234792158008


100%|██████████| 100/100 [00:06<00:00, 15.94it/s]


In [6]:
train_gen = DataGenerator(train_path_ids)
test_gen = DataGenerator(test_path_ids)

In [7]:
assert not np.allclose(train_gen[0][0][0], train_gen[0][0][0])
assert len(train_gen[0][0]) == 3
for i in range(3):
    get_set = train_gen[0][0][0]
    if len(get_set.shape) != 3:
        print(get_set)


In [8]:
def create_model():
    K.clear_session()
    GRU_DIM = 64

    history_inp = Input((LearningPlayer_v1.TIMESTEPS, LearningPlayer_v1.TIMESTEP_FEATURES), name='history_inp')
    move_inp = Input((LearningPlayer_v1.TIMESTEP_FEATURES, ), name='move_inp')
    hand_inp = Input((LearningPlayer_v1.HAND_FEATURES, ), name='hand_inp')
    gru = GRU(GRU_DIM, name='gru')(history_inp)

    concat = Concatenate()([gru, move_inp, hand_inp])
    hidden = Dense(64, activation='relu', name='hidden')(concat)

    output = Dense(1, activation='linear', name='output')(BatchNormalization(name='batchnorm')(hidden))
    combined_net = keras.models.Model(inputs=[history_inp, move_inp, hand_inp], outputs=output)
    combined_net.compile(loss=mean_squared_error, optimizer='adam', metrics=['mean_squared_error'])
    return combined_net

In [ ]:
def train_model(fname='model.h5'):
    combined_net = create_model()
    
    callbacks = [
        EarlyStopping(monitor='val_mean_squared_error', mode='min', verbose=1, patience=2),
        ModelCheckpoint(fname, monitor='val_mean_squared_error', mode='min', verbose=1, save_best_only=True)
    ]

    combined_net.fit_generator(train_gen,
              epochs=50,
                steps_per_epoch=2000,
            validation_steps=200,
              callbacks=callbacks,
              validation_data=test_gen,
              shuffle=True,
                workers=1,
                max_queue_size=200,
                use_multiprocessing=False
              )
    return combined_net

for i in range(1):
    train_model(data_folder + '_combined_' + str(i) + '.h5')

Epoch 1/50
  59/2000 [..............................] - ETA: 5:33 - loss: 0.8759 - mean_squared_error: 0.8759

In [13]:
import subprocess
def split_model(composite, model_folder):
    best_model = keras.models.load_model(composite)
    bn = best_model.layers[-2]
    history_net = keras.models.Model(inputs=[best_model.get_layer('history_inp').input], outputs=[best_model.get_layer('gru').output])

    vector_history_inp = Input((best_model.get_layer('gru').output.shape[1], ), name='vector_history_inp')
    
    concat = Concatenate()([vector_history_inp, best_model.get_layer('move_inp').output, best_model.get_layer('hand_inp').output])
    hidden = best_model.get_layer('hidden')(concat)
    output = best_model.get_layer('output')(bn(hidden))

    move_inp = best_model.get_layer('move_inp').input
    hand_inp = best_model.get_layer('hand_inp').input
    position_net = keras.models.Model(inputs=[vector_history_inp, move_inp, hand_inp], outputs=[output])

    history_net.save(str(model_folder / 'history.h5'))
    position_net.save(str(model_folder / 'position.h5'))
    

In [18]:
def sanity_check_model(combined_file, net_dir):
    sanity_set = train_gen[0]
    historical_features, move_vectors, hand_vectors = sanity_set[0]
    targets = sanity_set[1]

    player = LearningPlayer_v1(name='sanity', net_dir=str(net_dir))
    
    historical_matrix = player.history_net.predict(historical_features, batch_size=1024)

    from sklearn.metrics import mean_squared_error
    
    error_1 = mean_squared_error(targets, player.get_position_predictions(historical_matrix, move_vectors, hand_vectors))
    
    composite = keras.models.load_model(combined_file)
    error_2 = mean_squared_error(targets, composite.predict([historical_features, move_vectors, hand_vectors], batch_size=1024))
    print(combined_file, error_1, error_2)
    assert np.abs(error_1 - error_2) < 1E-2

In [21]:
from pathlib import Path

def delete_dir(path):
    if not os.path.exists(path):
        return
    for file in path.iterdir():
        os.remove(file)
    path.rmdir()

for i in range(16):
    combined_file = data_folder + '_combined_' + str(i) + '.h5'
    if os.path.exists(combined_file):
        model_folder_name = data_folder + '_model' + str(i)

        model_folder_path = Path('../models/', model_folder_name)
        delete_dir(model_folder_path)
        model_folder_path.mkdir()

        split_model(combined_file, model_folder_path)
        sanity_check_model(combined_file, model_folder_path)
        print(model_folder_name)
        subprocess.check_output(['gsutil', 'cp', '-r', '../models/' + model_folder_name + '/*', 'gs://landlord_ai/models/' + model_folder_name])

/opt/conda/lib/python3.7/site-packages/keras/engine/saving.py:341: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '


Model: "model_15"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
vector_history_inp (InputLayer) (None, 32)           0                                            
__________________________________________________________________________________________________
move_inp (InputLayer)           (None, 21)           0                                            
__________________________________________________________________________________________________
hand_inp (InputLayer)           (None, 18)           0                                            
__________________________________________________________________________________________________
concatenate_8 (Concatenate)     (None, 71)           0           vector_history_inp[0][0]         
                                                                 move_inp[0][0]            

/opt/conda/lib/python3.7/site-packages/keras/engine/saving.py:341: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '


Model: "model_17"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
vector_history_inp (InputLayer) (None, 64)           0                                            
__________________________________________________________________________________________________
move_inp (InputLayer)           (None, 21)           0                                            
__________________________________________________________________________________________________
hand_inp (InputLayer)           (None, 18)           0                                            
__________________________________________________________________________________________________
concatenate_9 (Concatenate)     (None, 103)          0           vector_history_inp[0][0]         
                                                                 move_inp[0][0]            

/opt/conda/lib/python3.7/site-packages/keras/engine/saving.py:341: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '


Model: "model_19"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
vector_history_inp (InputLayer) (None, 64)           0                                            
__________________________________________________________________________________________________
move_inp (InputLayer)           (None, 21)           0                                            
__________________________________________________________________________________________________
hand_inp (InputLayer)           (None, 18)           0                                            
__________________________________________________________________________________________________
concatenate_10 (Concatenate)    (None, 103)          0           vector_history_inp[0][0]         
                                                                 move_inp[0][0]            